title:       "Operating Systems 2021-1 (OS211)"
version:     "0031a---07-Mar-2021"
copyright:   "2021-2021"
description: >- 
  This Is How Me Do It!
  This Is How Me Do It!
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-6"
author:           "Mardianto"
address:          "Jambi"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://mardianto-byte.github.io/os211/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/mardianto-byte/os211/"
urlghpage:        "https://mardianto-byte.github.io/os211/"
keywords:         "jekyll, testing"
github:           [metadata]

